# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: npm build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 17.x]
        
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install dependencies
        run: npm ci
        working-directory: ./src/browser_extention/
        
      - run: npm run build:all
        working-directory: ./src/browser_extention/

      - name: Copy
        run: mkdir -p upload-dic && cp -fr  ./src/browser_extention/dist/source upload-dic
      - run: ls
      - run: ls ./src/browser_extention/dist/source
      - name: save chrome
        uses: actions/upload-artifact@v2
        with:
          name: chrome
          path: upload-dic/source/chrome
          if-no-files-found: error
          
      - name: save firefox
        uses: actions/upload-artifact@v2
        with:
          name: firefox
          path: upload-dic/source/safari
          if-no-files-found: error
        
      - name: save safari
        uses: actions/upload-artifact@v2
        with:
          name: chrome
          path: upload-dic/source/safari
          if-no-files-found: error
